#!/bin/bash

set -e

# Force push HEAD to baseline
echo "Reverting master to baseline tag"

git fetch origin --tags --force
git checkout master
git reset --hard baseline
git push origin baseline:master -f
